import type { Product, PriceFilter } from '../interface/Product.interface';

export const mockProducts: Product[] = [
    {
        id: '1',
        name: 'Complete React Developer in 2024',
        price: 899000,
        image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=300&fit=crop',
        shortDescription: 'Học React từ cơ bản đến nâng cao với các dự án thực tế',
        fullDescription: 'Khóa học React hoàn chỉnh từ cơ bản đến nâng cao. Bạn sẽ học được React hooks, Redux, TypeScript và xây dựng các ứng dụng thực tế. Khóa học bao gồm hơn 50 video bài giảng và 10 dự án thực hành.',
        category: 'Programming',
        rating: 4.8,
        reviews: 2540,
        instructor: 'Nguyễn Văn A',
        duration: '40 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['React', 'JavaScript', 'Web Development', 'Frontend']
    },
    {
        id: '2',
        name: 'Python for Data Science Masterclass',
        price: 1299000,
        image: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400&h=300&fit=crop',
        shortDescription: 'Khóa học Python cho khoa học dữ liệu với pandas, numpy, matplotlib',
        fullDescription: 'Khóa học toàn diện về Python cho khoa học dữ liệu. Học cách sử dụng pandas, numpy, matplotlib, seaborn và scikit-learn để phân tích và trực quan hóa dữ liệu. Bao gồm các dự án thực tế về machine learning.',
        category: 'Data Science',
        rating: 4.9,
        reviews: 1820,
        instructor: 'Trần Thị B',
        duration: '60 giờ',
        level: 'Beginner',
        isLiked: false,
        tags: ['Python', 'Data Science', 'Machine Learning', 'Analytics']
    },
    {
        id: '3',
        name: 'Digital Marketing Complete Course',
        price: 699000,
        image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
        shortDescription: 'Học marketing số từ A-Z: SEO, SEM, Social Media, Content Marketing',
        fullDescription: 'Khóa học marketing số toàn diện bao gồm SEO, Google Ads, Facebook Ads, Instagram Marketing, Content Marketing và Email Marketing. Học cách tạo chiến lược marketing hiệu quả và đo lường ROI.',
        category: 'Marketing',
        rating: 4.6,
        reviews: 3200,
        instructor: 'Lê Văn C',
        duration: '35 giờ',
        level: 'Beginner',
        isLiked: false,
        tags: ['Digital Marketing', 'SEO', 'Social Media', 'Google Ads']
    },
    {
        id: '4',
        name: 'UI/UX Design Fundamentals',
        price: 799000,
        image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=300&fit=crop',
        shortDescription: 'Thiết kế giao diện và trải nghiệm người dùng với Figma',
        fullDescription: 'Học các nguyên tắc cơ bản của UI/UX design, từ research người dùng đến wireframing, prototyping và testing. Sử dụng Figma để tạo ra các thiết kế chuyên nghiệp và user-friendly.',
        category: 'Design',
        rating: 4.7,
        reviews: 1560,
        instructor: 'Phạm Thị D',
        duration: '45 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['UI Design', 'UX Design', 'Figma', 'Prototyping']
    },
    {
        id: '5',
        name: 'Node.js Backend Development',
        price: 999000,
        image: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=300&fit=crop',
        shortDescription: 'Xây dựng API và ứng dụng backend với Node.js, Express, MongoDB',
        fullDescription: 'Khóa học phát triển backend với Node.js từ cơ bản đến nâng cao. Học Express.js, MongoDB, authentication, API design, testing và deployment. Xây dựng các ứng dụng backend thực tế.',
        category: 'Programming',
        rating: 4.8,
        reviews: 2100,
        instructor: 'Hoàng Văn E',
        duration: '55 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['Node.js', 'Express', 'MongoDB', 'Backend', 'API']
    },
    {
        id: '6',
        name: 'English Communication for Business',
        price: 599000,
        image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=300&fit=crop',
        shortDescription: 'Tiếng Anh giao tiếp trong môi trường doanh nghiệp',
        fullDescription: 'Nâng cao khả năng giao tiếp tiếng Anh trong môi trường làm việc. Học cách thuyết trình, đàm phán, viết email chuyên nghiệp và tham gia các cuộc họp quốc tế một cách tự tin.',
        category: 'Language',
        rating: 4.5,
        reviews: 2800,
        instructor: 'Sarah Johnson',
        duration: '30 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['English', 'Business Communication', 'Presentation', 'Writing']
    },
    {
        id: '7',
        name: 'Advanced Machine Learning Specialization',
        price: 1499000,
        image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400&h=300&fit=crop',
        shortDescription: 'Deep Learning, Neural Networks và AI Applications',
        fullDescription: 'Khóa học chuyên sâu về Machine Learning với các chủ đề nâng cao như Deep Learning, Neural Networks, Computer Vision và Natural Language Processing.',
        category: 'Data Science',
        rating: 4.9,
        reviews: 1250,
        instructor: 'Dr. Alex Chen',
        duration: '65 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['Machine Learning', 'Deep Learning', 'AI', 'Neural Networks']
    },
    {
        id: '8',
        name: 'Financial Trading & Investment',
        price: 1299000,
        image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=300&fit=crop',
        shortDescription: 'Phân tích kỹ thuật và đầu tư chứng khoán chuyên nghiệp',
        fullDescription: 'Học cách phân tích thị trường chứng khoán, các chiến lược giao dịch, quản lý rủi ro và xây dựng danh mục đầu tư hiệu quả.',
        category: 'Business',
        rating: 4.7,
        reviews: 890,
        instructor: 'Michael Wong',
        duration: '50 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Trading', 'Investment', 'Stock Market', 'Finance']
    },
    {
        id: '9',
        name: 'Advanced Adobe Photoshop Masterclass',
        price: 899000,
        image: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=400&h=300&fit=crop',
        shortDescription: 'Thành thạo Photoshop với các kỹ thuật chuyên nghiệp',
        fullDescription: 'Khám phá các kỹ thuật nâng cao trong Photoshop, từ chỉnh sửa ảnh chuyên nghiệp đến digital art và photo manipulation.',
        category: 'Design',
        rating: 4.8,
        reviews: 1560,
        instructor: 'Lisa Parker',
        duration: '45 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['Photoshop', 'Digital Art', 'Photo Editing', 'Design']
    },
    {
        id: '10',
        name: 'Japanese for Beginners',
        price: 699000,
        image: 'https://images.unsplash.com/photo-1528164344705-47542687000d?w=400&h=300&fit=crop',
        shortDescription: 'Học tiếng Nhật cơ bản cho người mới bắt đầu',
        fullDescription: 'Khóa học tiếng Nhật cho người mới bắt đầu, tập trung vào ngữ pháp cơ bản, từ vựng và hội thoại thông dụng.',
        category: 'Language',
        rating: 4.6,
        reviews: 2100,
        instructor: 'Tanaka Yuki',
        duration: '40 giờ',
        level: 'Beginner',
        isLiked: false,
        tags: ['Japanese', 'Language Learning', 'Beginner Japanese']
    },
    {
        id: '11',
        name: 'Content Marketing Strategy',
        price: 799000,
        image: 'https://images.unsplash.com/photo-1542435503-956c469947f6?w=400&h=300&fit=crop',
        shortDescription: 'Xây dựng chiến lược content marketing hiệu quả',
        fullDescription: 'Học cách xây dựng và thực thi chiến lược content marketing, từ nghiên cứu đối tượng đến tạo content và đo lường hiệu quả.',
        category: 'Marketing',
        rating: 4.7,
        reviews: 1850,
        instructor: 'Emma Thompson',
        duration: '35 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Content Marketing', 'Digital Marketing', 'Strategy']
    },
    {
        id: '12',
        name: 'Flutter Mobile Development',
        price: 1199000,
        image: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=400&h=300&fit=crop',
        shortDescription: 'Phát triển ứng dụng di động đa nền tảng với Flutter',
        fullDescription: 'Học cách xây dựng ứng dụng mobile cho iOS và Android với Flutter framework. Bao gồm state management, API integration và deployment.',
        category: 'Programming',
        rating: 4.8,
        reviews: 1320,
        instructor: 'David Kumar',
        duration: '55 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Flutter', 'Mobile Development', 'Dart', 'Cross-platform']
    },
    {
        id: '13',
        name: 'Data Analysis with Python',
        price: 999000,
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop',
        shortDescription: 'Phân tích dữ liệu với Python và các thư viện phổ biến',
        fullDescription: 'Khóa học toàn diện về phân tích dữ liệu với Python, sử dụng pandas, numpy và matplotlib. Thực hành với các dự án thực tế.',
        category: 'Data Science',
        rating: 4.9,
        reviews: 2200,
        instructor: 'John Smith',
        duration: '50 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Python', 'Data Analysis', 'Pandas', 'Numpy']
    },
    {
        id: '14',
        name: 'Product Management Essentials',
        price: 899000,
        image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
        shortDescription: 'Các kỹ năng cần thiết cho Product Manager',
        fullDescription: 'Học các kỹ năng cốt lõi của Product Management: định nghĩa sản phẩm, roadmap, agile, user research và data-driven decision making.',
        category: 'Business',
        rating: 4.7,
        reviews: 1650,
        instructor: 'Sarah Chen',
        duration: '40 giờ',
        level: 'Beginner',
        isLiked: false,
        tags: ['Product Management', 'Agile', 'Business Strategy']
    },
    {
        id: '15',
        name: '3D Modeling with Blender',
        price: 1099000,
        image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=300&fit=crop',
        shortDescription: 'Học thiết kế 3D với phần mềm Blender',
        fullDescription: 'Khóa học toàn diện về modeling 3D với Blender, từ cơ bản đến nâng cao. Học cách tạo nhân vật, môi trường và animation.',
        category: 'Design',
        rating: 4.8,
        reviews: 980,
        instructor: 'Mike Anderson',
        duration: '60 giờ',
        level: 'Beginner',
        isLiked: false,
        tags: ['3D Modeling', 'Blender', 'Animation', 'Design']
    },
    {
        id: '16',
        name: 'AWS Cloud Architecture',
        price: 1599000,
        image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=300&fit=crop',
        shortDescription: 'Thiết kế và triển khai kiến trúc cloud với AWS',
        fullDescription: 'Học cách thiết kế và triển khai các giải pháp cloud scalable trên AWS. Bao gồm EC2, S3, Lambda, và các services khác.',
        category: 'Programming',
        rating: 4.9,
        reviews: 1450,
        instructor: 'James Wilson',
        duration: '70 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['AWS', 'Cloud Computing', 'DevOps', 'Architecture']
    },
    {
        id: '17',
        name: 'Blockchain Development with Solidity',
        price: 1699000,
        image: 'https://images.unsplash.com/photo-1639322537228-f710d846310a?w=400&h=300&fit=crop',
        shortDescription: 'Phát triển ứng dụng blockchain với Ethereum và Solidity',
        fullDescription: 'Khóa học chuyên sâu về phát triển blockchain, smart contracts với Solidity và Ethereum. Xây dựng DApps và tích hợp Web3.',
        category: 'Programming',
        rating: 4.8,
        reviews: 890,
        instructor: 'Vitalik Chen',
        duration: '65 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['Blockchain', 'Ethereum', 'Solidity', 'Smart Contracts']
    },
    {
        id: '18',
        name: 'Advanced Excel for Business Analytics',
        price: 799000,
        image: 'https://images.unsplash.com/photo-1509475826633-fed577a2c71b?w=400&h=300&fit=crop',
        shortDescription: 'Phân tích dữ liệu kinh doanh với Excel nâng cao',
        fullDescription: 'Học các kỹ thuật phân tích dữ liệu nâng cao trong Excel: Pivot Tables, Power Query, DAX, và Power BI integration.',
        category: 'Business',
        rating: 4.7,
        reviews: 2100,
        instructor: 'Robert Miller',
        duration: '45 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Excel', 'Business Analytics', 'Data Analysis', 'Power BI']
    },
    {
        id: '19',
        name: 'Motion Graphics with After Effects',
        price: 1299000,
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=300&fit=crop',
        shortDescription: 'Thiết kế motion graphics chuyên nghiệp với After Effects',
        fullDescription: 'Khóa học toàn diện về motion graphics, animation và visual effects với Adobe After Effects. Thực hành với các dự án thực tế.',
        category: 'Design',
        rating: 4.8,
        reviews: 1560,
        instructor: 'Jessica Lee',
        duration: '55 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['After Effects', 'Motion Graphics', 'Animation', 'Visual Effects']
    },
    {
        id: '20',
        name: 'Korean Language and Culture',
        price: 899000,
        image: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=400&h=300&fit=crop',
        shortDescription: 'Học tiếng Hàn và văn hóa Hàn Quốc từ cơ bản',
        fullDescription: 'Khóa học tiếng Hàn toàn diện, bao gồm ngữ pháp, từ vựng, hội thoại và văn hóa Hàn Quốc. Phù hợp cho người mới bắt đầu.',
        category: 'Language',
        rating: 4.9,
        reviews: 2800,
        instructor: 'Kim Min Ji',
        duration: '50 giờ',
        level: 'Beginner',
        isLiked: false,
        tags: ['Korean', 'Language Learning', 'Korean Culture']
    },
    {
        id: '21',
        name: 'Game Development with Unity',
        price: 1499000,
        image: 'https://images.unsplash.com/photo-1556438064-2d7646166914?w=400&h=300&fit=crop',
        shortDescription: 'Phát triển game 2D và 3D với Unity Engine',
        fullDescription: 'Khóa học toàn diện về phát triển game với Unity. Học cách tạo game 2D, 3D, physics, animation và game mechanics.',
        category: 'Programming',
        rating: 4.8,
        reviews: 1750,
        instructor: 'Thomas Anderson',
        duration: '70 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Unity', 'Game Development', 'C#', '3D Games']
    },
    {
        id: '22',
        name: 'Chinese for Business',
        price: 999000,
        image: 'https://images.unsplash.com/photo-1523294587484-bae6cc870010?w=400&h=300&fit=crop',
        shortDescription: 'Tiếng Trung thương mại cho doanh nhân',
        fullDescription: 'Khóa học tiếng Trung chuyên sâu cho môi trường kinh doanh. Học cách đàm phán, giao tiếp và văn hóa kinh doanh Trung Quốc.',
        category: 'Language',
        rating: 4.7,
        reviews: 1200,
        instructor: 'Wang Li Wei',
        duration: '45 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Chinese', 'Business Chinese', 'Language Learning']
    },
    {
        id: '23',
        name: 'Advanced Data Visualization',
        price: 1299000,
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop',
        shortDescription: 'Trực quan hóa dữ liệu nâng cao với D3.js và Python',
        fullDescription: 'Học cách tạo các biểu đồ tương tác và dashboard phức tạp với D3.js, Python và các công cụ visualization hiện đại.',
        category: 'Data Science',
        rating: 4.9,
        reviews: 980,
        instructor: 'David Zhang',
        duration: '50 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['Data Visualization', 'D3.js', 'Python', 'Analytics']
    },
    {
        id: '24',
        name: 'Social Media Marketing Mastery',
        price: 899000,
        image: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=400&h=300&fit=crop',
        shortDescription: 'Chiến lược marketing trên mạng xã hội toàn diện',
        fullDescription: 'Học cách xây dựng và thực thi chiến lược marketing hiệu quả trên Facebook, Instagram, LinkedIn và TikTok.',
        category: 'Marketing',
        rating: 4.7,
        reviews: 2400,
        instructor: 'Sophie Brown',
        duration: '40 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Social Media', 'Digital Marketing', 'Content Strategy']
    },
    {
        id: '25',
        name: 'Vue.js Advanced Patterns',
        price: 1199000,
        image: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=300&fit=crop',
        shortDescription: 'Các pattern nâng cao trong Vue.js và Vuex',
        fullDescription: 'Khám phá các pattern nâng cao trong Vue.js: Composition API, custom hooks, advanced routing, state management với Vuex.',
        category: 'Programming',
        rating: 4.8,
        reviews: 1100,
        instructor: 'Evan You',
        duration: '45 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['Vue.js', 'JavaScript', 'Frontend', 'Web Development']
    },
    {
        id: '26',
        name: 'Investment Banking Fundamentals',
        price: 1599000,
        image: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=400&h=300&fit=crop',
        shortDescription: 'Các kiến thức cơ bản về ngân hàng đầu tư',
        fullDescription: 'Khóa học toàn diện về ngân hàng đầu tư: valuation, M&A, financial modeling, và investment banking career path.',
        category: 'Business',
        rating: 4.9,
        reviews: 850,
        instructor: 'Morgan Stanley',
        duration: '60 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['Investment Banking', 'Finance', 'Business', 'M&A']
    },
    {
        id: '27',
        name: 'Advanced UI Animation',
        price: 999000,
        image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&h=300&fit=crop',
        shortDescription: 'Animation nâng cao cho UI/UX với GSAP và Framer Motion',
        fullDescription: 'Học cách tạo các animation phức tạp và mượt mà cho web interface sử dụng GSAP, Framer Motion và CSS animations.',
        category: 'Design',
        rating: 4.8,
        reviews: 1200,
        instructor: 'Sarah Davis',
        duration: '35 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['UI Animation', 'GSAP', 'Framer Motion', 'Web Design']
    },
    {
        id: '28',
        name: 'Natural Language Processing',
        price: 1399000,
        image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&h=300&fit=crop',
        shortDescription: 'Xử lý ngôn ngữ tự nhiên với Python và Deep Learning',
        fullDescription: 'Khám phá các kỹ thuật NLP hiện đại: transformers, BERT, word embeddings và ứng dụng trong chatbots và text analysis.',
        category: 'Data Science',
        rating: 4.9,
        reviews: 780,
        instructor: 'Dr. Emily Watson',
        duration: '55 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['NLP', 'Python', 'Deep Learning', 'AI']
    },
    {
        id: '29',
        name: 'French for Travelers',
        price: 699000,
        image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&h=300&fit=crop',
        shortDescription: 'Tiếng Pháp cơ bản cho người đi du lịch',
        fullDescription: 'Học tiếng Pháp thực tế cho du lịch: giao tiếp cơ bản, đặt phòng, gọi món, mua sắm và xử lý tình huống thường gặp.',
        category: 'Language',
        rating: 4.6,
        reviews: 2100,
        instructor: 'Marie Dubois',
        duration: '25 giờ',
        level: 'Beginner',
        isLiked: false,
        tags: ['French', 'Travel', 'Language Learning', 'Conversation']
    },
    {
        id: '30',
        name: 'Cybersecurity Fundamentals',
        price: 1299000,
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=300&fit=crop',
        shortDescription: 'Bảo mật thông tin và an ninh mạng cơ bản',
        fullDescription: 'Khóa học toàn diện về bảo mật: network security, cryptography, ethical hacking, và best practices trong cybersecurity.',
        category: 'Programming',
        rating: 4.8,
        reviews: 1600,
        instructor: 'John McAfee',
        duration: '50 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Cybersecurity', 'Network Security', 'Ethical Hacking']
    },
    {
        id: '31',
        name: 'Digital Illustration with Procreate',
        price: 899000,
        image: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=400&h=300&fit=crop',
        shortDescription: 'Vẽ minh họa số với Procreate trên iPad',
        fullDescription: 'Khóa học toàn diện về digital illustration với Procreate: brushes, layers, animation và các kỹ thuật vẽ chuyên nghiệp.',
        category: 'Design',
        rating: 4.7,
        reviews: 1800,
        instructor: 'Anna White',
        duration: '40 giờ',
        level: 'Beginner',
        isLiked: false,
        tags: ['Digital Art', 'Procreate', 'Illustration', 'iPad']
    },
    {
        id: '32',
        name: 'DevOps with Kubernetes',
        price: 1599000,
        image: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=400&h=300&fit=crop',
        shortDescription: 'Container orchestration và cloud-native development',
        fullDescription: 'Học cách triển khai và quản lý ứng dụng với Kubernetes, microservices architecture và cloud-native practices.',
        category: 'Programming',
        rating: 4.9,
        reviews: 920,
        instructor: 'Kelsey Hightower',
        duration: '65 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['Kubernetes', 'DevOps', 'Cloud Native', 'Docker']
    },
    {
        id: '33',
        name: 'Business Strategy and Innovation',
        price: 1299000,
        image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop',
        shortDescription: 'Chiến lược kinh doanh và đổi mới sáng tạo',
        fullDescription: 'Khóa học về xây dựng chiến lược kinh doanh, quản lý đổi mới, và phát triển mô hình kinh doanh bền vững.',
        category: 'Business',
        rating: 4.8,
        reviews: 1100,
        instructor: 'Peter Drucker',
        duration: '45 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Strategy', 'Innovation', 'Business Model', 'Management']
    },
    {
        id: '34',
        name: 'Advanced SEO Techniques',
        price: 999000,
        image: 'https://images.unsplash.com/photo-1571371102955-75809c14698f?w=400&h=300&fit=crop',
        shortDescription: 'Kỹ thuật SEO nâng cao và Technical SEO',
        fullDescription: 'Khóa học chuyên sâu về SEO: technical SEO, content optimization, link building và SEO strategy cho e-commerce.',
        category: 'Marketing',
        rating: 4.7,
        reviews: 1600,
        instructor: 'Brian Dean',
        duration: '40 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['SEO', 'Digital Marketing', 'Technical SEO', 'Content Strategy']
    },
    {
        id: '35',
        name: 'German Business Communication',
        price: 899000,
        image: 'https://images.unsplash.com/photo-1527866959252-deab85ef7d1b?w=400&h=300&fit=crop',
        shortDescription: 'Tiếng Đức trong môi trường kinh doanh',
        fullDescription: 'Học tiếng Đức chuyên ngành kinh doanh: giao tiếp văn phòng, đàm phán, viết email và văn hóa kinh doanh Đức.',
        category: 'Language',
        rating: 4.6,
        reviews: 890,
        instructor: 'Hans Mueller',
        duration: '45 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['German', 'Business German', 'Language Learning']
    },
    {
        id: '36',
        name: 'iOS App Development with SwiftUI',
        price: 1499000,
        image: 'https://images.unsplash.com/photo-1621839673705-6617adf9e890?w=400&h=300&fit=crop',
        shortDescription: 'Phát triển ứng dụng iOS hiện đại với SwiftUI',
        fullDescription: 'Học cách xây dựng ứng dụng iOS với SwiftUI framework, Combine, và các design patterns phổ biến trong iOS development.',
        category: 'Programming',
        rating: 4.8,
        reviews: 1250,
        instructor: 'Tim Cook',
        duration: '60 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['iOS', 'SwiftUI', 'Mobile Development', 'Apple']
    },
    {
        id: '37',
        name: 'Financial Modeling in Excel',
        price: 1299000,
        image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400&h=300&fit=crop',
        shortDescription: 'Mô hình hóa tài chính chuyên nghiệp với Excel',
        fullDescription: 'Xây dựng các mô hình tài chính phức tạp trong Excel: DCF valuation, LBO models, merger models và financial projections.',
        category: 'Business',
        rating: 4.9,
        reviews: 980,
        instructor: 'Michael Bloomberg',
        duration: '50 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['Financial Modeling', 'Excel', 'Finance', 'Valuation']
    },
    {
        id: '38',
        name: 'Character Design for Animation',
        price: 999000,
        image: 'https://images.unsplash.com/photo-1616512659455-111d3367649f?w=400&h=300&fit=crop',
        shortDescription: 'Thiết kế nhân vật cho phim hoạt hình và game',
        fullDescription: 'Học cách thiết kế và phát triển nhân vật cho animation và game. Bao gồm character design, expression sheets và character rigging.',
        category: 'Design',
        rating: 4.8,
        reviews: 1450,
        instructor: 'Maya Johnson',
        duration: '45 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Character Design', 'Animation', 'Game Art', 'Digital Art']
    },
    {
        id: '39',
        name: 'Big Data with Apache Spark',
        price: 1599000,
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop',
        shortDescription: 'Xử lý dữ liệu lớn với Apache Spark',
        fullDescription: 'Khóa học chuyên sâu về big data processing với Apache Spark: RDDs, Spark SQL, MLlib và streaming data processing.',
        category: 'Data Science',
        rating: 4.9,
        reviews: 760,
        instructor: 'Dr. Hadoop',
        duration: '55 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['Big Data', 'Apache Spark', 'Data Processing', 'Analytics']
    },
    {
        id: '40',
        name: 'Email Marketing Automation',
        price: 799000,
        image: 'https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=300&fit=crop',
        shortDescription: 'Chiến lược và tự động hóa email marketing',
        fullDescription: 'Học cách xây dựng và tự động hóa chiến dịch email marketing: segmentation, automation flows, A/B testing và analytics.',
        category: 'Marketing',
        rating: 4.7,
        reviews: 1850,
        instructor: 'Laura Martinez',
        duration: '35 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Email Marketing', 'Marketing Automation', 'Digital Marketing']
    },
    {
        id: '41',
        name: 'Microservices Architecture',
        price: 1699000,
        image: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=400&h=300&fit=crop',
        shortDescription: 'Thiết kế và triển khai microservices',
        fullDescription: 'Học cách thiết kế, phát triển và triển khai microservices architecture. Bao gồm service discovery, API gateway và event-driven architecture.',
        category: 'Programming',
        rating: 4.9,
        reviews: 890,
        instructor: 'Martin Fowler',
        duration: '65 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['Microservices', 'System Design', 'Architecture', 'Cloud']
    },
    {
        id: '42',
        name: 'Digital Product Design',
        price: 1199000,
        image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=300&fit=crop',
        shortDescription: 'Thiết kế sản phẩm số từ ý tưởng đến prototype',
        fullDescription: 'Khóa học toàn diện về thiết kế sản phẩm số: research, wireframing, prototyping và design systems. Thực hành với các dự án thực tế.',
        category: 'Design',
        rating: 4.8,
        reviews: 1650,
        instructor: 'Sarah Cooper',
        duration: '50 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Product Design', 'UX Design', 'Prototyping', 'Design Systems']
    },
    {
        id: '43',
        name: 'Startup Growth Hacking',
        price: 999000,
        image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop',
        shortDescription: 'Chiến lược tăng trưởng cho startup',
        fullDescription: 'Học các chiến lược growth hacking hiệu quả: user acquisition, activation, retention và revenue optimization cho startup.',
        category: 'Business',
        rating: 4.7,
        reviews: 1200,
        instructor: 'Sean Ellis',
        duration: '40 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Growth Hacking', 'Startup', 'Marketing', 'Business Strategy']
    },
    {
        id: '44',
        name: 'Advanced Computer Vision',
        price: 1599000,
        image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&h=300&fit=crop',
        shortDescription: 'Computer Vision và Deep Learning nâng cao',
        fullDescription: 'Khám phá các kỹ thuật computer vision hiện đại: object detection, image segmentation, face recognition và video analysis.',
        category: 'Data Science',
        rating: 4.9,
        reviews: 780,
        instructor: 'Dr. Vision',
        duration: '60 giờ',
        level: 'Advanced',
        isLiked: false,
        tags: ['Computer Vision', 'Deep Learning', 'AI', 'Python']
    },
    {
        id: '45',
        name: 'Business English Writing',
        price: 799000,
        image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=300&fit=crop',
        shortDescription: 'Kỹ năng viết tiếng Anh trong kinh doanh',
        fullDescription: 'Học cách viết email chuyên nghiệp, báo cáo, proposal và các tài liệu kinh doanh bằng tiếng Anh.',
        category: 'Language',
        rating: 4.6,
        reviews: 2200,
        instructor: 'Emily Parker',
        duration: '30 giờ',
        level: 'Intermediate',
        isLiked: false,
        tags: ['Business English', 'Writing', 'Communication', 'Professional English']
    }
];

export const priceFilters: PriceFilter[] = [
    { min: 0, max: 500000, label: 'Dưới 500K' },
    { min: 500000, max: 1000000, label: '500K - 1 triệu' },
    { min: 1000000, max: Infinity, label: 'Trên 1 triệu' }
];

export const categories = [
    'Tất cả',
    'Programming',
    'Data Science',
    'Marketing',
    'Design',
    'Language',
    'Business'
];

export const levels = [
    'Tất cả',
    'Beginner',
    'Intermediate',
    'Advanced'
]; 